name: CI-Multi-Jobs

on:
  push:
    branches:
      - workflow_branch
  workflow_dispatch:

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run before build
        run: |
          sudo apt-get install -y tree
          tree .
      - name: Run build
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build	
          python -m build
      - name: Run ls
        run: |
          ls -la 
      - name: Install tree & run after build
        run: |
          sudo apt-get install -y tree
          tree .
